### ISSUE TITLE
モデルの利用規約についてのご確認

### ISSUE THREAD

**Issue by Stereoarts** [NanJ-Programming-Team/Yumemirebananashi#1]
こちらのプロジェクトに含まれるモデル「やきう民」について、利用規約に違反しています。
具体的に、以下の部分が該当します。

- 本モデル未改造状態での再配布

著作者への明示的な利用の許可を申請するか、gitignoire の設定をお願い致します。
同様の違反が続く場合は、こちらも何らかの対処が必要になってきますのでご留意ください。

**Comment by ReNeeter** [comment]
Issueありがとうございます。
gitignoireに設定しGitHub上からも削除します。
申し訳ありませんでした。

**Comment by Stereoarts** [comment]
迅速な対応ありがとうございます。状況を見つつですが一旦 close します。
